name: brewingdevelopments
favicon: null
layout_spectrum: 0.90368
typography_spectrum: 0.54804
title: Brewing Developments
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#1c1612'
    - '#c79a6e'
    - '#addde2'
    - '#ff8100'
  brandStrength: 0.1875
  lightness: 0.46172449504956603
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
