name: brewingdevelopments
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54804
title: BREWING DEVELOPMENTS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00001c'
    - '#fefee2'
    - '#b5ad89'
    - '#7c061c'
    - '#7c6965'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
