name: brewingdevelopments
favicon: null
layout_spectrum: 0.24218
typography_spectrum: 0.54804
title: Brewing Developments
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#200c03'
    - '#612b04'
    - '#8f968f'
    - '#3c4c72'
  brandStrength: 0.125
  lightness: 0.46172449504956603
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
